### ISSUE TITLE
copyedit

### ISSUE THREAD

**Issue by MarcScott** [raspberrypilearning/getting-started-with-microbits#1]
Hi @LornaLynch and @lauraclay 

Could I get a copy-edit on this one please.
A couple of points:
- MicroPython is with capitals in the middle, but all one word.
- mu should always be lower-case m
- micro:bit should always be lower-case m and with the annoying colon in the middle.

Thanks in advance

**Comment by lauraclay** [comment]
All done, although that middle colon in micro:bit still gives me a murderous twitch...!

**Comment by MarcScott** [comment]
I know, I end up just finding and replacing to add it in at the end for the whole document. It's horrible.
Cheers for the copy edit.
