### ISSUE TITLE
Missing hardware items

### ISSUE THREAD

**Issue by lurch** [raspberrypilearning/getting-started-with-microbits#8]
https://www.raspberrypi.org/learning/getting-started-with-microbit/requirements/ currently just lists a microbit and a USB cable. But in the "MORE FEATURES OF THE MICRO:BIT" section it also uses a resistor, an LED, a couple of crocodile clip cables and a female-female jumper lead.

I guess you _could_ argue that this is already covered by the "If you have access to an LED, a resistor and some leads, you can connect up the micro:bit to the components as shown below. If you don't, then no need to worry." text, in which case feel free to close this issue.

**Comment by MarcScott** [comment]
@samalderhyde Could I get the picture of the 47‎Ω resistor used in this resource added to the components repo please.

**Comment by MarcScott** [comment]
47r added to components and hardware links added

**Comment by lurch** [comment]
Great :) Looks like you forgot to add the LED though, and I'm not sure why it says "Crocodile clips and wite" ?

**Comment by MarcScott** [comment]
And done. Cheers for nagging :)
